services:
  postgres:
    image: postgres:16-alpine
    container_name: url-shortener_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-url-shortener_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-url-shortener_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: url-shortener_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: url-shortener_app
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - .:/app
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      APP_URL: ${APP_URL}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRY: ${JWT_EXPIRY}
      DEFAULT_REFRESH_EXPIRY: ${DEFAULT_REFRESH_EXPIRY}
      SHORT_REFRESH_EXPIRY: ${SHORT_REFRESH_EXPIRY}
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
